version: '2'
services:
    filebeat:
        container_name: filebeat_test
        image: docker.elastic.co/beats/filebeat:7.6.1
        volumes:
            - /root/filebit/log:/usr/share/filebeat/logs
            - /root/filebit/filebeat.yml:/usr/share/filebeat/filebeat.yml
            - /root/filebit/tmp:/tmp/filebeat
