filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /usr/share/filebeat/logs/test.log
output.file:
  path: "/tmp/filebeat"
  filename: filebeat
output.logstash:
  hosts: ["178.33.243.229:5044"]

